import Link from 'next/link';
import { notFound } from 'next/navigation';
import {
  Badge,
  Button,
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  Container,
  Heading,
  Stack,
  Text,
} from '@sparx/ui';
import { ArrowLeft } from 'lucide-react';
import { api, type ApiRestError } from '@/lib/api-rest-client';
import { AssetEditForm } from './edit-form';

export const dynamic = 'force-dynamic';

interface MediaAssetDetail {
  id: string;
  key: string;
  original_filename: string;
  mime_type: string;
  byte_size: string;
  width: number | null;
  height: number | null;
  blurhash: string | null;
  dominant_color: string | null;
  focal_point: { x: number; y: number };
  alt_text: string | null;
  caption: string | null;
  status: string;
  processing_error: string | null;
  usage_count: number;
  variants: {
    id: string;
    format: string;
    width: number;
    height: number;
    byte_size: string;
    url: string;
  }[];
  original_url: string | null;
  created_at: string;
  updated_at: string;
}

export default async function AssetPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  let asset: MediaAssetDetail;
  try {
    asset = await api.get<MediaAssetDetail>(`/v1/media/assets/${id}`);
  } catch (err) {
    if ((err as ApiRestError).status === 404) notFound();
    throw err;
  }

  const isImage = asset.mime_type.startsWith('image/');
  const preview =
    asset.variants.find((v) => v.format === 'webp' && v.width >= 800)?.url ??
    asset.variants[0]?.url ??
    asset.original_url;

  return (
    <Container size="xl">
      <Stack gap={6} className="py-10">
        <Stack gap={2}>
          <Button variant="link" size="sm" asChild>
            <Link href="/cms/media">
              <ArrowLeft className="h-3.5 w-3.5" />
              Back to media
            </Link>
          </Button>
          <Heading level={1}>{asset.original_filename}</Heading>
          <Stack direction="row" gap={2} align="center">
            <Badge variant={asset.status === 'ready' ? 'success' : 'outline'}>{asset.status}</Badge>
            <Text size="sm" variant="muted">
              {asset.width && asset.height && `${asset.width}×${asset.height} · `}
              {asset.mime_type}
            </Text>
          </Stack>
          {asset.processing_error && (
            <Text size="sm" variant="danger">
              Transcode failed: {asset.processing_error}
            </Text>
          )}
        </Stack>

        <div className="grid gap-6 lg:grid-cols-[2fr_1fr]">
          <Card>
            <CardHeader>
              <Heading level={3}>Preview &amp; focal point</Heading>
              <CardDescription>
                Click anywhere on the image to set the focal point — crops in non-uniform aspect
                ratios will center on that pixel.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <AssetEditForm
                assetId={asset.id}
                isImage={isImage}
                previewUrl={preview}
                altText={asset.alt_text}
                caption={asset.caption}
                focalPoint={asset.focal_point}
              />
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <Heading level={3}>Variants</Heading>
              <CardDescription>
                Auto-generated by the media-worker — drop these into <code>&lt;picture&gt;</code>{' '}
                with AVIF first.
              </CardDescription>
            </CardHeader>
            <CardContent>
              {asset.variants.length === 0 ? (
                <Text size="sm" variant="muted">
                  No variants yet. {asset.status === 'uploading' && 'Transcode pending.'}
                </Text>
              ) : (
                <Stack gap={2}>
                  {asset.variants.map((v) => (
                    <Stack
                      key={v.id}
                      direction="row"
                      align="center"
                      gap={3}
                      className="rounded-md bg-[var(--color-bg-subtle)] px-3 py-2 text-sm"
                    >
                      <Badge variant="outline">{v.format.toUpperCase()}</Badge>
                      <Text size="sm">{v.width}px</Text>
                      <Text size="xs" variant="muted" className="ml-auto">
                        {formatBytes(Number(v.byte_size))}
                      </Text>
                    </Stack>
                  ))}
                </Stack>
              )}
            </CardContent>
          </Card>
        </div>
      </Stack>
    </Container>
  );
}

function formatBytes(n: number): string {
  if (!n || n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / (1024 * 1024)).toFixed(1)} MB`;
}
