// Regenerates `src/openapi.d.ts` from a running api-rest instance.
//
// Usage:
//   pnpm --filter @sparx/api-client gen
//   SPARX_OPENAPI_URL=http://localhost:3000/v1/openapi.json pnpm --filter @sparx/api-client gen
//
// In CI you'd start api-rest in test mode (no port collision) and dump the
// spec by calling app.swagger() directly. For now this script assumes
// api-rest is already running locally or in cluster and the env var points
// at the live spec URL.

import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = join(__dirname, '..', 'src', 'openapi.d.ts');
const SPEC_URL = process.env.SPARX_OPENAPI_URL ?? 'http://localhost:3000/v1/openapi.json';

async function main(): Promise<void> {
  console.log(`Fetching OpenAPI spec from ${SPEC_URL}`);
  const ast = await openapiTS(new URL(SPEC_URL), {
    additionalProperties: false,
    emptyObjectsUnknown: true,
  });
  const contents = `// AUTO-GENERATED by scripts/generate-types.ts — do not edit by hand.
// Source: ${SPEC_URL}
// Re-run \`pnpm --filter @sparx/api-client gen\` after api-rest changes.

${astToString(ast)}
`;
  writeFileSync(OUT_PATH, contents, 'utf8');
  console.log(`Wrote ${OUT_PATH}`);
}

void main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
