export { prisma } from './client';
export { withTenant } from './tenant-context';
export type { TenantContext, TxClient } from './tenant-context';

export type {
  Tenant,
  User,
  Session,
  Account,
  Verification,
  AuditLog,
  // CMS
  Page,
  ContentType,
  ContentEntry,
  ContentRevision,
  ContentReference,
  Taxonomy,
  TaxonomyTerm,
  EntryTaxonomyTerm,
  Author,
  Redirect,
  NavigationMenu,
  NavigationItem,
  PreviewToken,
  WebhookSubscription,
  WebhookDelivery,
  MediaAsset,
  MediaVariant,
  // CRM
  Customer,
  CustomerAddress,
  B2BAccount,
  Pipeline,
  PipelineStage,
  Deal,
  DealOrder,
  DealQuote,
  CrmActivity,
  Task,
  Segment,
  SegmentMember,
  SavedView,
  // CRM — orders + child tables
  Order,
  OrderItem,
  OrderPayment,
  OrderRefund,
  OrderRefundItem,
  OrderFulfillment,
  OrderFulfillmentItem,
  // CRM — quotes
  Quote,
  QuoteItem,
  Prisma,
} from '@prisma/client';
