apiVersion: v1
kind: Namespace
metadata:
  name: sparx-prod
  labels:
    name: sparx-prod
    env: prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
