import * as React from 'react';
import { render } from '@react-email/render';
import { getEmailProvider } from './providers';
import type { DeliveryResult, SendableEmail } from './types';
import {
  PasswordResetEmail,
  passwordResetSubject,
  type PasswordResetEmailProps,
} from './templates/password-reset';
import {
  WelcomeMerchantEmail,
  welcomeMerchantSubject,
  type WelcomeMerchantEmailProps,
} from './templates/welcome-merchant';

// Template registry + dispatcher. Two surfaces:
//
//   renderTemplate(input)  — pure render → returns SendableEmail. Used by
//                            email-worker, which then hands the result to
//                            getEmailProvider().send().
//
//   sendTemplate(input)    — render + provider.send. Direct-send escape
//                            hatch for synchronous-required flows (OTP).
//                            New emails MUST publish 'email.send' to
//                            Pub/Sub instead — see CLAUDE.md.

const DEFAULT_FROM_ENV = 'SPARX_EMAIL_FROM';
const FALLBACK_FROM = 'Sparx <noreply@sparx.email>';

function defaultFrom(): string {
  return process.env[DEFAULT_FROM_ENV] ?? FALLBACK_FROM;
}

export type TemplateId = 'password-reset' | 'welcome-merchant';

export type TemplateSend =
  | {
      template: 'password-reset';
      to: string;
      props: PasswordResetEmailProps;
      from?: string;
      replyTo?: string;
    }
  | {
      template: 'welcome-merchant';
      to: string;
      props: WelcomeMerchantEmailProps;
      from?: string;
      replyTo?: string;
    };

/**
 * Render a typed template to a SendableEmail (subject + html + auto-generated
 * plain text). Used by email-worker to render after pulling an `email.send`
 * Pub/Sub message; also used internally by sendTemplate().
 *
 * Plain text is generated by React Email's `render(..., { plainText: true })`
 * — never hand-write a separate text version, it just drifts from the HTML.
 */
export async function renderTemplate(input: TemplateSend): Promise<SendableEmail> {
  switch (input.template) {
    case 'password-reset': {
      const element = <PasswordResetEmail {...input.props} />;
      const [html, text] = await Promise.all([
        render(element),
        render(element, { plainText: true }),
      ]);
      return {
        from: input.from ?? defaultFrom(),
        to: input.to,
        replyTo: input.replyTo,
        subject: passwordResetSubject,
        html,
        text,
        templateId: 'password-reset',
      };
    }
    case 'welcome-merchant': {
      const element = <WelcomeMerchantEmail {...input.props} />;
      const [html, text] = await Promise.all([
        render(element),
        render(element, { plainText: true }),
      ]);
      return {
        from: input.from ?? defaultFrom(),
        to: input.to,
        replyTo: input.replyTo,
        subject: welcomeMerchantSubject,
        html,
        text,
        templateId: 'welcome-merchant',
      };
    }
  }
}

/**
 * Direct send. Renders the template and immediately hands it to the provider
 * (console in dev, Postal in prod).
 *
 * @deprecated for general use — publish an `email.send` Pub/Sub event so
 * email-worker handles delivery, retries, and audit. This direct path
 * remains for synchronous-required flows only (OTP codes, future 2FA).
 * Adding a new caller? See CLAUDE.md → "Outbound email".
 */
export async function sendTemplate(input: TemplateSend): Promise<DeliveryResult> {
  const rendered = await renderTemplate(input);
  return sendEmail(rendered);
}

/**
 * Hand-rolled SendableEmail → provider escape hatch. Same direct-send
 * caveat as sendTemplate.
 *
 * @deprecated for general use — see sendTemplate doc.
 */
export async function sendEmail(email: SendableEmail): Promise<DeliveryResult> {
  return getEmailProvider().send(email);
}

export { renderTemplate as _renderTemplateForTest };
