import * as React from 'react';
import { render } from '@react-email/render';
import { getEmailProvider } from './providers';
import { BrandProvider, type BrandTokens } from './components';
import { EmailLayout } from './templates/_layout';
import type { DeliveryResult, SendableEmail } from './types';
import {
  PasswordResetEmail,
  passwordResetSubject,
  type PasswordResetEmailProps,
} from './templates/password-reset';
import {
  WelcomeMerchantEmail,
  welcomeMerchantSubject,
  type WelcomeMerchantEmailProps,
} from './templates/welcome-merchant';

// Template registry + dispatcher. Two surfaces:
//
//   renderTemplate(input)  — pure render → returns SendableEmail. Used by
//                            email-worker, which then hands the result to
//                            getEmailProvider().send().
//
//   sendTemplate(input)    — render + provider.send. Direct-send escape
//                            hatch for synchronous-required flows (OTP).
//                            New emails MUST publish 'email.send' to
//                            Pub/Sub instead — see CLAUDE.md.

const DEFAULT_FROM_ENV = 'SPARX_EMAIL_FROM';
const FALLBACK_FROM = 'Sparx <noreply@sparx.email>';

function defaultFrom(): string {
  return process.env[DEFAULT_FROM_ENV] ?? FALLBACK_FROM;
}

export type TemplateId = 'password-reset' | 'welcome-merchant';

export type TemplateSend =
  | {
      template: 'password-reset';
      to: string;
      props: PasswordResetEmailProps;
      from?: string;
      replyTo?: string;
    }
  | {
      template: 'welcome-merchant';
      to: string;
      props: WelcomeMerchantEmailProps;
      from?: string;
      replyTo?: string;
    };

/**
 * Render a typed template to a SendableEmail (subject + html + auto-generated
 * plain text). Used by email-worker to render after pulling an `email.send`
 * Pub/Sub message; also used internally by sendTemplate().
 *
 * Plain text is generated by React Email's `render(..., { plainText: true })`
 * — never hand-write a separate text version, it just drifts from the HTML.
 */
export interface RenderTemplateOptions {
  /** Per-tenant brand. When omitted, the Sparx defaults render. Platform
   *  emails (OTP/2FA, system) intentionally pass no brand. */
  brand?: Partial<BrandTokens>;
}

export async function renderTemplate(
  input: TemplateSend,
  opts: RenderTemplateOptions = {}
): Promise<SendableEmail> {
  // Wrap the template in the brand provider so every atom (via context) picks
  // up the tenant's colors/fonts/logo without per-template prop threading.
  const wrap = (node: React.ReactElement) => (
    <BrandProvider brand={opts.brand}>{node}</BrandProvider>
  );

  switch (input.template) {
    case 'password-reset': {
      const element = wrap(<PasswordResetEmail {...input.props} />);
      const [html, text] = await Promise.all([
        render(element),
        render(element, { plainText: true }),
      ]);
      return {
        from: input.from ?? defaultFrom(),
        to: input.to,
        replyTo: input.replyTo,
        subject: passwordResetSubject,
        html,
        text,
        templateId: 'password-reset',
      };
    }
    case 'welcome-merchant': {
      const element = wrap(<WelcomeMerchantEmail {...input.props} />);
      const [html, text] = await Promise.all([
        render(element),
        render(element, { plainText: true }),
      ]);
      return {
        from: input.from ?? defaultFrom(),
        to: input.to,
        replyTo: input.replyTo,
        subject: welcomeMerchantSubject,
        html,
        text,
        templateId: 'welcome-merchant',
      };
    }
  }
}

/**
 * Direct send. Renders the template and immediately hands it to the provider
 * (console in dev, Postal in prod).
 *
 * @deprecated for general use — publish an `email.send` Pub/Sub event so
 * email-worker handles delivery, retries, and audit. This direct path
 * remains for synchronous-required flows only (OTP codes, future 2FA).
 * Adding a new caller? See CLAUDE.md → "Outbound email".
 */
export async function sendTemplate(input: TemplateSend): Promise<DeliveryResult> {
  const rendered = await renderTemplate(input);
  return sendEmail(rendered);
}

/**
 * Hand-rolled SendableEmail → provider escape hatch. Same direct-send
 * caveat as sendTemplate.
 *
 * @deprecated for general use — see sendTemplate doc.
 */
export async function sendEmail(email: SendableEmail): Promise<DeliveryResult> {
  return getEmailProvider().send(email);
}

export interface AuthoredEmailInput {
  to: string;
  subject: string;
  /** Sanitized HTML body (e.g. from @sparx/cms-editor's renderDocToHtml). */
  bodyHtml: string;
  preheader?: string;
  from?: string;
  replyTo?: string;
}

/**
 * Render a merchant-AUTHORED marketing email: the brand chrome (header/footer/
 * background from BrandTokens) wrapping sanitized prose HTML. The body HTML is
 * injected verbatim — callers MUST pass already-sanitized HTML (the CMS
 * serializer whitelists tags/URLs). Used by broadcasts + authored templates.
 *
 * Until the shared section-composition system lands (plan P9), the body is a
 * single rich-text region; section blocks layer on later without changing this
 * signature.
 */
export async function renderAuthoredEmail(
  input: AuthoredEmailInput,
  opts: RenderTemplateOptions = {}
): Promise<SendableEmail> {
  const element = (
    <BrandProvider brand={opts.brand}>
      <EmailLayout preview={input.preheader ?? input.subject}>
        <div dangerouslySetInnerHTML={{ __html: input.bodyHtml }} />
      </EmailLayout>
    </BrandProvider>
  );
  const [html, text] = await Promise.all([render(element), render(element, { plainText: true })]);
  return {
    from: input.from ?? defaultFrom(),
    to: input.to,
    replyTo: input.replyTo,
    subject: input.subject,
    html,
    text,
  };
}

export { renderTemplate as _renderTemplateForTest };
