// Public media variants — serves the world-readable derivative renditions
// generated by media-worker.
//
//   GET /v1/public/media/variants/:tenantId/:assetId/:filename
//     where :filename = `${format}-${width}.${ext}` (e.g. `webp-800.webp`)
//
// Why this exists: the org enforces iam.allowedPolicyMemberDomains, which
// forbids granting allUsers:objectViewer on any GCS bucket. So variants
// live in a private bucket and api-rest reads them with the app SA + pipes
// the bytes back to the client with long-cache headers. Cloudflare in front
// of api.sparx.works absorbs all repeat traffic at the edge; api-rest only
// sees first-miss requests per (variant, edge POP).
//
// No auth required. The key shape is deterministic (tenantId + assetId +
// format/width), so enumerating across tenants buys you nothing — without
// the assetId you can't construct a hit, and assetIds are UUIDs we issued.

import type { FastifyPluginAsync } from 'fastify';
import { z } from 'zod';
import { getStorage, variantKey } from '../../../lib/storage.js';
import { notFound } from '@sparx/api-core/errors';

// Filename pattern matches what variantKey() emits in storage.ts:
//   `${format}-${width}.${ext}` → e.g. webp-800.webp, avif-1200.avif, jpeg-400.jpg
const FILENAME_RE = /^([a-z]+)-(\d+)\.([a-z0-9]+)$/;

const PathParams = z.object({
  tenantId: z.string().uuid(),
  assetId: z.string().uuid(),
  filename: z.string().regex(FILENAME_RE),
});

// Content-type sniff from the variant filename extension. We trust the
// extension because the worker is the only writer and writes deterministic
// names; the bucket-level GCS metadata is also set, but reading it would
// cost a second round-trip.
const CONTENT_TYPES: Record<string, string> = {
  avif: 'image/avif',
  webp: 'image/webp',
  jpeg: 'image/jpeg',
  jpg: 'image/jpeg',
  png: 'image/png',
};

const publicMediaRoutes: FastifyPluginAsync = (app) => {
  app.get<{ Params: z.infer<typeof PathParams> }>(
    '/v1/public/media/variants/:tenantId/:assetId/:filename',
    async (request, reply) => {
      const params = PathParams.parse(request.params);
      // PathParams.regex already validated the filename matches FILENAME_RE,
      // so the re-exec cannot return null. Re-execing is just to destructure.
      const match = FILENAME_RE.exec(params.filename)!;
      const [, format, widthStr, ext] = match;

      const key = variantKey(params.tenantId, params.assetId, format!, Number(widthStr), ext!);

      let obj;
      try {
        obj = await getStorage().readObject(key);
      } catch {
        // GCS returns 404 by surfacing an ENOENT-shaped error inside the
        // node SDK. Anything else (auth, network) bubbles up to the
        // generic error handler as 500.
        throw notFound('MediaVariant', `${params.assetId}/${params.filename}`);
      }

      // Long-cache aggressively — variant content for a given key is
      // immutable (the worker re-encodes to a new key on re-process).
      // Cloudflare honours these headers; first edge miss hits api-rest,
      // every subsequent request is served from CF cache.
      reply
        .header('cache-control', 'public, max-age=31536000, immutable')
        .header(
          'content-type',
          CONTENT_TYPES[ext!] ?? obj.contentType ?? 'application/octet-stream'
        );
      if (obj.size !== null) reply.header('content-length', String(obj.size));

      return reply.send(obj.body);
    }
  );

  return Promise.resolve();
};

export default publicMediaRoutes;
