apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddy-data
  namespace: sparx-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 5Gi
