apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  namespace: sparx-prod
spec:
  type: ClusterIP
  ports:
    - name: pgbouncer
      port: 5432
      targetPort: 5432
  selector:
    app: pgbouncer
